import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SparklesPreview } from '@/components/ui/SparklesPreview';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Companion',
  description: 'Generated by create next app',
  icons: {
    icon: '/companion-logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-black`}>
        {/* <SparklesPreview /> */}
        {}
        <main>{children}</main>
      </body>
    </html>
  );
}
