version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

  flask:
    build: ./back
    container_name: flask-app
    environment:
      - MONGO_URI=mongodb://mongo:27017/companion_db
      - SECRET_KEY=dev-secret-key
    ports:
      - '5001:5000'
    depends_on:
      - mongo

volumes:
  mongo_data:
